#
# Corrected & Customized OpenWrt Build Configuration
#
name: Build Custom OpenWrt for ZN-M2

on:
  workflow_dispatch: # Allows you to manually click "Run workflow" to trigger the build

env:
  REPO_URL: https://github.com/openwrt/openwrt.git
  REPO_BRANCH: main # You can change this to a more stable version, e.g., openwrt-23.05
  CONFIG_FILE: .config
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout # Checks-out your repository's code (to access the patches directory)
      uses: actions/checkout@v4

    - name: Install build environment dependencies
      run: |
        sudo apt update
        # Here is the fix: replaced python3-distutils with python3-setuptools
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
        gettext git libncurses5-dev libssl-dev python3-setuptools rsync unzip zlib1g-dev \
        file wget

    - name: Clone OpenWrt source code
      run: |
        git clone --depth 1 -b $REPO_BRANCH $REPO_URL openwrt

    - name: Update Feeds and apply your patches
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        # Critical step: Copy the patches from your repository into the OpenWrt source
        cp -r ../patches .

    - name: Generate your custom .config file
      run: |
        cd openwrt
        rm -f .config # Remove old .config
        # Write your specified configuration
        cat <<EOF > .config
        # --- 1. Device Model Settings ---
        CONFIG_TARGET_ipq60xx_generic_DEVICE_cmcc_zn-m2=y
        CONFIG_TARGET_ipq60xx_generic=y

        # --- 2. Package Selection ---
        # --- Basic Functions & Language ---
        CONFIG_PACKAGE_luci=y
        CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
        CONFIG_PACKAGE_luci-theme-design=y
        # --- Network Core Services ---
        CONFIG_PACKAGE_luci-app-gecoosac=y
        CONFIG_PACKAGE_luci-app-ddns-go=y
        CONFIG_PACKAGE_luci-app-sqm=y
        CONFIG_PACKAGE_luci-proto-wireguard=y
        CONFIG_PACKAGE_wireguard-tools=y
        CONFIG_PACKAGE_luci-app-upnp=y
        # --- Ad Blocking & Proxies ---
        CONFIG_PACKAGE_luci-app-adguardhome=y
        CONFIG_PACKAGE_luci-app-openclash=y
        CONFIG_PACKAGE_luci-app-unblockneteasemusic=y
        # --- Containers & Virtualization ---
        CONFIG_PACKAGE_luci-app-dockerman=y
        # --- System Tools & Monitoring ---
        CONFIG_PACKAGE_luci-app-ttyd=y
        CONFIG_PACKAGE_luci-app-wrtbwmon=y
        CONFIG_PACKAGE_luci-app-nlbwmon=y
        CONFIG_PACKAGE_luci-app-wol=y
        CONFIG_PACKAGE_htop=y
        CONFIG_PACKAGE_nano=y
        # --- Smart Home ---
        CONFIG_PACKAGE_luci-app-mosquitto=y
        EOF

        make defconfig

    - name: Download source code packages
      run: |
        cd openwrt
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      run: |
        cd openwrt
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s

    - name: Organize and upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt-ZN-M2-firmware-Custom
        path: openwrt/bin/targets/
