#
# 最终正确版 - OpenWrt 编译配置 (使用最新稳定版 24.10, 移除WIFI)
#
name: Build Latest Stable OpenWrt for ZN-M2 (No-WiFi)

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/openwrt/openwrt.git
  
  # ✅ 使用核实后的最新稳定版分支: openwrt-24.10
  REPO_BRANCH: openwrt-24.10
  
  CONFIG_FILE: .config
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: 安装编译环境依赖
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
        gettext git libncurses5-dev libssl-dev python3-setuptools rsync unzip zlib1g-dev \
        file wget

    - name: 克隆 OpenWrt 源码
      run: |
        git clone --depth 1 -b $REPO_BRANCH $REPO_URL openwrt

    - name: 更新 Feeds 并应用你的补丁
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        cp -r ../patches .

    - name: 生成你的定制 .config 文件
      run: |
        cd openwrt
        rm -f .config
        cat <<EOF > .config
        # --- 1. 设备型号设置 ---
        CONFIG_TARGET_ipq60xx_generic_DEVICE_cmcc_zn-m2=y
        CONFIG_TARGET_ipq60xx_generic=y

        # --- 2. 软件包选择 ---
        CONFIG_PACKAGE_luci=y
        CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
        CONFIG_PACKAGE_luci-theme-design=y
        CONFIG_PACKAGE_luci-app-gecoosac=y
        CONFIG_PACKAGE_luci-app-ddns-go=y
        CONFIG_PACKAGE_luci-app-sqm=y
        CONFIG_PACKAGE_luci-proto-wireguard=y
        CONFIG_PACKAGE_wireguard-tools=y
        CONFIG_PACKAGE_luci-app-upnp=y
        CONFIG_PACKAGE_luci-app-adguardhome=y
        CONFIG_PACKAGE_luci-app-openclash=y
        CONFIG_PACKAGE_luci-app-unblockneteasemusic=y
        CONFIG_PACKAGE_luci-app-dockerman=y
        CONFIG_PACKAGE_luci-app-ttyd=y
        CONFIG_PACKAGE_luci-app-wrtbwmon=y
        CONFIG_PACKAGE_luci-app-nlbwmon=y
        CONFIG_PACKAGE_luci-app-wol=y
        CONFIG_PACKAGE_htop=y
        CONFIG_PACKAGE_nano=y
        CONFIG_PACKAGE_luci-app-mosquitto=y

        # --- 3. 移除 Wi-Fi 组件 ---
        # CONFIG_PACKAGE_kmod-ath11k is not set
        # CONFIG_PACKAGE_wpad-basic-wolfssl is not set
        # CONFIG_PACKAGE_hostapd-common is not set
        # CONFIG_PACKAGE_wireless-regdb is not set

        EOF
        make defconfig

    - name: 下载源码包
      run: |
        cd openwrt
        make download -j8

    - name: 开始编译固件
      run: |
        cd openwrt
        make -j$(nproc) V=s

    - name: 整理并上传固件
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt-ZN-M2-firmware-24.10-NoWiFi
        path: openwrt/bin/targets/
